version: '3.0'

services:

  neo4j:
    build:
      context: ./src
    image: semanticpie/neo4j:${IMAGE_TAG:-latest}
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474" # Go to http://localhost:7474/browser/ after bootstrapping
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./kb:/kb/
