version: '3.0'

services:

  neo4j:
    build:
      context: .
    image: semanticpie/neo4j:${IMAGE_TAG:-latest}
    environment:
      # - NEO4J_AUTH=neo4j/test # Just click on the login button without password
      - NEO4J_AUTH=none # Just click on the login button without password
    ports:
      - "7474:7474" # Go to http://localhost:7474/browser/ after bootstrapping
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./cypher_query.cql:/cyphers/interviews.cql
